import type {Metadata} from "next";
import type {ReactNode} from "react";
import  "./globals.css";
import localFont from "next/font/local";
// import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <h1>begin</h1>
        <div>
            {children}
        </div>
        <h1>end</h1>
        </body>
        </html>
    );
}
