import "./globals.css";

import type {Metadata} from "next";
import localFont from "next/font/local";
import type {JSX, ReactNode} from "react";
// Import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    description: "Generated by create next app",
    title: "Create Next App",
};

export default function RootLayout({children}: Readonly<{children: ReactNode}>): JSX.Element {
    return (
        <html lang="en">
            <head>
                <title>title</title>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <h1>begin</h1>
                <div>{children}</div>
                <h1>end</h1>
            </body>
        </html>
    );
}
